dbt_core_gcloud:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: bigquery
      method: "{{ env_var('DBT_BQ_METHOD', 'oauth') }}"
      project: "{{ env_var('DBT_GCP_PROJECT_DEV') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET', 'analytics_' ~ env_var('DBT_USER', 'local')) }}"
      location: "{{ env_var('DBT_BQ_LOCATION', 'US') }}"
      threads: 4
      priority: "{{ env_var('DBT_BQ_PRIORITY', 'interactive') }}"
      labels:
        service: dbt
        env: "{{ env_var('DBT_TARGET', 'dev') }}"
      maximum_bytes_billed: "{{ (env_var('DBT_MAX_BYTES_BILLED', '') | as_number) if env_var('DBT_MAX_BYTES_BILLED', '') else none }}"
      job_execution_timeout_seconds: "{{ (env_var('DBT_JOB_EXECUTION_TIMEOUT_SEC', '') | as_number) if env_var('DBT_JOB_EXECUTION_TIMEOUT_SEC', '') else none }}"
    ci:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      project: "{{ env_var('DBT_GCP_PROJECT_CI') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET') }}"
      location: "{{ env_var('DBT_BQ_LOCATION', 'US') }}"
      threads: 4
      priority: "{{ env_var('DBT_BQ_PRIORITY', 'interactive') }}"
      labels:
        service: dbt
        env: "{{ env_var('DBT_TARGET', 'ci') }}"
      maximum_bytes_billed: "{{ (env_var('DBT_MAX_BYTES_BILLED', '') | as_number) if env_var('DBT_MAX_BYTES_BILLED', '') else none }}"
      job_execution_timeout_seconds: "{{ (env_var('DBT_JOB_EXECUTION_TIMEOUT_SEC', '') | as_number) if env_var('DBT_JOB_EXECUTION_TIMEOUT_SEC', '') else none }}"
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_GCP_PROJECT_PROD') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET_PROD', 'analytics') }}"
      location: "{{ env_var('DBT_BQ_LOCATION', 'US') }}"
      threads: 8
      priority: "{{ env_var('DBT_BQ_PRIORITY', 'interactive') }}"
      labels:
        service: dbt
        env: "{{ env_var('DBT_TARGET', 'prod') }}"
      maximum_bytes_billed: "{{ (env_var('DBT_MAX_BYTES_BILLED', '') | as_number) if env_var('DBT_MAX_BYTES_BILLED', '') else none }}"
      job_execution_timeout_seconds: "{{ (env_var('DBT_JOB_EXECUTION_TIMEOUT_SEC', '') | as_number) if env_var('DBT_JOB_EXECUTION_TIMEOUT_SEC', '') else none }}"
